### ISSUE TITLE
Should we use the provided ClientID?

### ISSUE THREAD

**Issue by StevenFischerWI** [bmello4688/TDAmeritradeApi#2]
Hi there,

I'm having issues with the API working with anything besides the demo ClientID (consumer key). When I replace it with my consumer key the API fails to connect. Is the intention to use the project's ClientID as it is registered with TDA? Or should I keep troubleshooting why my Client ID fails?

I successfully use my Client ID for other purposes so I know it's working. Thanks for your help and the great library!

**Comment by bmello4688** [comment]
ClientID (consumer key) is just an example. You need to use the one generated in the My Apps located here:

https://developer.tdameritrade.com/user/me/apps
