### ISSUE TITLE
Your Coffee is returning a perms error

### ISSUE THREAD

**Issue by justSteve** [bmello4688/TDAmeritradeApi#5]
Looking to send  a th$ but clicking the Paypal returns: 
You do not have permission to access or perform operations on this resource.

(I'm able to log into my paypal acct via the submitted email)

**Comment by bmello4688** [comment]
Sorry Steve, I'm not sure what's wrong it could be the web site having an issue. I added the alternative site

http://ko-fi.com/brianmello

Try that out instead.

**Comment by justSteve** [comment]
Worked -- thx!
